apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "microservices-demo"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: kaulei
  lifecycle: experimental
